### ISSUE TITLE
Number of files not showing after upload 

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#609]
#### Describe the bug
Number of files not showing after upload 

#### To Reproduce
Steps to reproduce the behaviour:

**Comment by fmorelloCSC** [comment]
I leave it in the comment because I can not modify the issue somehow.

1) Drag-drop the data in SD Connect
2) Click on encrypt and upload
3) When upload is finished I return to the browser view where all the bucket are listed
4) the bucket that was created during the upload is now listed there, but it displays that there is 0 files in it.
5) If I open the bucket (even if is shows that no data are there), I can see all the encrypted files in it
